name: Compilation & tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  nano_build:
    name: Build Ravencoin application for NanoS, X and S+
    strategy:
      matrix:
        include:
          - SDK: "$NANOS_SDK"
            model: nanos
          - SDK: "$NANOX_SDK"
            model: nanox
          - SDK: "$NANOSP_SDK"
            model: nanosp
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder-lite:latest
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Build
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          make BOLOS_SDK=${{ matrix.SDK }} COIN=ravencoin_testnet
          mv bin/app.elf "bin/ravencoin_test_${{ matrix.model }}.elf"
      - name: Upload app binary
        uses: actions/upload-artifact@v3
        with:
          name: apps
          path: bin/*.elf

  job_functional_test:
    name: Functional tests with Ragger (compatible with Speculos & physical devices)
    needs:
      - nano_build
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Download app binary
        uses: actions/download-artifact@v3
        with:
          name: apps
          path: tests-legacy/elfs
      - name: Install tests dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y qemu-user-static
          pip install --extra-index-url https://test.pypi.org/simple/ -r tests-legacy/requirements.txt
      - name: Run test
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: pytest --tb=short -v tests-legacy/
